name: example

dependencies:
  meta: any
  tape:
    path: ../tape
  freezed_annotation: any

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  tapegen:
    path: ../tapegen
