name: flutter_taped
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/marcelgarus/tape

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tape: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  tapegen: ^0.0.2
