name: flutter_taped
description: A package containing tape adapters for flutter. Intended to be used with flutter and tape.
version: 0.0.1
homepage: https://github.com/marcelgarus/tape

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tape:
    path: ../../tape

dev_dependencies:
  flutter_test:
    sdk: flutter
  tapegen:
    path: ../../tapegen
