[package]
name = "tape"
version = "0.1.0"
authors = ["Marcel Garus <marcel.garus@gmail.com>"]
edition = "2018"

# [lib]
# name = "pad"
# path = "src/parser.rs"

[[bin]]
name = "tape"
path = "src/main.rs"

[dependencies]
clap = "2.26.0"
num = "0.2.1"
semver = "0.7.0"
