name: tapegen
description: Tool for generating code for tape, a type-safe and future- and backwards-compatible serializer for Dart objects.
version: 0.0.2
homepage: https://github.com/marcelgarus/tape
issue_tracker: https://github.com/marcelgarus/tape/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.8
  args: ^1.6.0
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  console: ^3.1.0
  dart_style: ^1.3.6
  dartx: ^0.4.1
  glob: ^1.2.0
  meta: ^1.1.0
  path: ^1.6.4
  pub_semver: ^1.4.4
  pubspec_parse: ^0.1.5
  source_gen: ^0.9.0
  string_similarity: ^1.0.1
  tape:
    path: ../tape
  watcher: ^0.9.7+15
  yaml: ^2.2.1

dev_dependencies:
  build_test: ^0.10.11
  build_runner: ^1.7.4
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
  test: any
