name: tapegen
description: Tool for generating code for tape, a type-safe and future- and backwards-compatible serializer for Dart objects.
version: 0.0.1
homepage: https://github.com/marcelgarus/tape
issue_tracker: https://github.com/marcelgarus/tape/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.4
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  meta: ^1.1.0
  source_gen: ^0.9.0
  watcher: ^0.9.7+15
  pub_semver: ^1.4.4
  dartx: ^0.4.1
  args: ^1.6.0
  glob: any
  tape:
    path: ../tape
  yaml: ^2.2.1

dev_dependencies:
  build_test: ^0.10.11
  build_runner: ^1.7.4
  test: ^1.6.0
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
