name: tape
description: A serializer for Dart objects that is completely type-safe and future- and backwards-compatible.
version: 0.0.3
homepage: https://github.com/marcelgarus/tape
issue_tracker: https://github.com/marcelgarus/tape/issues/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8 # for @required annotation
  test: ^1.14.5
  collection: ^1.14.12

  # Dependencies for the CLI
  analyzer: ^0.39.8
  string_similarity: ^1.0.1
  args: ^1.6.0
  pubspec_parse: ^0.1.5
  console: ^3.1.0

dev_dependencies:
  build_runner: any
  tapegen:
    path: ../tapegen
