name: tape
description: A serializer for Dart objects that is completely type-safe and future- and backwards-compatible.
version: 0.0.3
homepage: https://github.com/marcelgarus/tape
issue_tracker: https://github.com/marcelgarus/tape/issues/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8 # for @required annotation
  collection: ^1.14.12

dev_dependencies:
  build_runner: any
  test: any
  tapegen:
    path: ../tapegen
