name: tape
description: A serializer for Dart objects that is completely type-safe and future- and backwards-compatible.
version: 0.0.2
homepage: https://github.com/marcelgarus/tape
issue_tracker: https://github.com/marcelgarus/tape/issues/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8 # for @required annotation
  test: any
  collection: any

  # Dependencies for the CLI
  analyzer: any
  string_similarity: any
  args: any
  pubspec_parse: any
  console: any

dev_dependencies:
  build_runner: any
  tapegen:
    path: ../tapegen
