name: tape
description: A serializer for Dart objects that is completely type-safe and future- and backwards-compatible.
version: 0.0.2
homepage: https://github.com/marcelgarus/tape

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  freezed_annotation: any # for @Default annotation interoperability
  meta: ^1.1.8 # for @required annotation
  test: any
  collection: any

dev_dependencies:
  build_runner: any
  freezed: any # for @Default annotation interoperability
