name: tape
description: A serializer for Dart objects that is completely type-safe and future- and backwards-compatible.
version: 0.0.2
homepage: https://github.com/marcelgarus/tape

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
